### ISSUE TITLE
Replace Stepper and MessageBox in MessageBox view

### ISSUE THREAD

**Issue by davidsowerby** [KrailOrg/krail-testApp#33]
Old add-ons - use something better, or update them, whichever is best

**Comment by mcollovati** [comment]
Latest versions of `MessageBox` has no client side component so they don't need widgetset compilation.
Stepper is already at latest available version

**Comment by davidsowerby** [comment]
As long as the test proves that a component's widgetset has been properly compiled, it does not matter what is used.  Please use whatever you feel is appropriate and remove anything that is not needed.

**Comment by davidsowerby** [comment]
Fixed by #42
